// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // FlutterFire a veces no genera entrada Linux. Misma app Firebase que web
        // para poder desarrollar en escritorio; para producción: flutterfire configure
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ifdT1ZCMcqBZWRa2-A01ANR0XoIt6HU',
    appId: '1:917698609166:web:3a79daf4551a5506e4fc5f',
    messagingSenderId: '917698609166',
    projectId: 'dolarsabio-496005',
    authDomain: 'dolarsabio-496005.firebaseapp.com',
    storageBucket: 'dolarsabio-496005.firebasestorage.app',
    measurementId: 'G-JJ2VYCWY0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfELiMxeKOPSqC6oyMomvkPSKHZn3vxUw',
    appId: '1:917698609166:android:2a50ab617a70b608e4fc5f',
    messagingSenderId: '917698609166',
    projectId: 'dolarsabio-496005',
    storageBucket: 'dolarsabio-496005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcdrqpp-YWo4H71T50O9KmIfZKdpNJu7o',
    appId: '1:917698609166:ios:78f34c8196ba8c7de4fc5f',
    messagingSenderId: '917698609166',
    projectId: 'dolarsabio-496005',
    storageBucket: 'dolarsabio-496005.firebasestorage.app',
    iosBundleId: 'com.kevin.dolarsabio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcdrqpp-YWo4H71T50O9KmIfZKdpNJu7o',
    appId: '1:917698609166:ios:78f34c8196ba8c7de4fc5f',
    messagingSenderId: '917698609166',
    projectId: 'dolarsabio-496005',
    storageBucket: 'dolarsabio-496005.firebasestorage.app',
    iosBundleId: 'com.kevin.dolarsabio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ifdT1ZCMcqBZWRa2-A01ANR0XoIt6HU',
    appId: '1:917698609166:web:2f335e65687c92b8e4fc5f',
    messagingSenderId: '917698609166',
    projectId: 'dolarsabio-496005',
    authDomain: 'dolarsabio-496005.firebaseapp.com',
    storageBucket: 'dolarsabio-496005.firebasestorage.app',
    measurementId: 'G-K75LCH0QJ3',
  );

  /// Linux (escritorio): misma configuración que [web] hasta registrar app Linux en Firebase.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB2ifdT1ZCMcqBZWRa2-A01ANR0XoIt6HU',
    appId: '1:917698609166:web:3a79daf4551a5506e4fc5f',
    messagingSenderId: '917698609166',
    projectId: 'dolarsabio-496005',
    authDomain: 'dolarsabio-496005.firebaseapp.com',
    storageBucket: 'dolarsabio-496005.firebasestorage.app',
    measurementId: 'G-JJ2VYCWY0C',
  );
}
